name: first-ci

on: 
 push:
   branches:
    - main 
 workflow_dispatch: 

jobs:
  lint:
    environment: dev
    env: 
     PASS: ${{ secrets.PASS_USER }}
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code 
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package/lock.json') }}

      - name: Install NodeJs 
        uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          ls
          cd angular
          npm ci

      - name: Run test
        run: |
          cd angular
          npm run lint

      - name: Build apk
        run: |
          cd angular
          npm run build
          echo $PASS
          echo "Usuario: ${{ vars.NAME_USER }}  "
          echo "${{ secrets.PASS_USER }}"



  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code 
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package/lock.json') }}

      - name: Install dependencies
        run: |
          cd angular
          npm ci

      - name: Test code
        run: |
          cd angular
          npm run test

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
           name: test-report
           path: angular/test.json

  build:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Get Code 
        uses: actions/checkout@v3

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package/lock.json') }}

      - name: Install dependencies
        run: |
          cd angular
          npm ci

      - name: Build apk
        run: |
          cd angular
          npm run 

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
           name: dist-files
           path: angular/dist

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Get build artifacts 
        uses: actions/download-artifact@v8
        with:
           name: dist-files
      - name: see files
        run: |
          ls

